// frontend-react-ts/src/views/ColorView.tsx
import { useEffect, useState } from "react";
import { ListOfColors } from "../domains/ListOfColors";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faPlus, faTrash } from "@fortawesome/free-solid-svg-icons";
import GetColorService from "../services/GetColorService";

const ColorView = () => {
  const [listOfColors, setListOfColors] = useState<ListOfColors>({
    data: [],
  });
  useEffect(() => {
    GetColorService.list().then((value) => setListOfColors(value));
  }, []);
  let content;
  if (listOfColors.data.length) {
    content = (
      <table className="table is-fullwidth">
        <thead>
          <tr>
            <th>Name</th>
            <th>Hex</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {listOfColors.data.map(({ name, hex }) => (
            <tr key={name}>
              <th>{name}</th>
              <th>{hex}</th>
              <th>
                <button className="button is-danger">
                  <span className="icon">
                    <FontAwesomeIcon icon={faTrash} />
                  </span>
                </button>
              </th>
            </tr>
          ))}
        </tbody>
      </table>
    );
  } else {
    content = (
      <section className="notification is-warning is-light">
        <h2 className="subtitle is-2">No colors, yet.</h2>
        <p>No colors in the system, yet! Create a new one!</p>
      </section>
    );
  }

  return (
    <>
      <div className="is-flex is-justify-content-end">
        <button className="button is-primary is-large is-rounded">
          <span className="icon">
            <FontAwesomeIcon icon={faPlus} />
          </span>
          <span>Create</span>
        </button>
      </div>
      <div className="mt-2">{content}</div>
    </>
  );
};

export default ColorView;

// frontend-vue-ts/src/views/ColorView.vue
<script setup lang="ts">
import { onBeforeMount, ref } from "vue";
import { ListOfColors } from "../domains/ListOfColors";
import GetColorService from "../services/GetColorService";

const listOfColors = ref<ListOfColors>({
  data: [],
});

onBeforeMount(() => {
  GetColorService.list().then((response) => (listOfColors.value = response));
});
</script>

<template>
  <div class="is-flex is-justify-content-end">
    <button class="button is-rounded is-primary is-large">
      <span class="icon">
        <font-awesome-icon icon="fa-solid fa-plus" />
      </span>
      <span>Create</span>
    </button>
  </div>
  <div class="mt-2">
    <table class="table is-fullwidth" v-if="listOfColors.data.length">
      <thead>
        <tr>
          <th>Name</th>
          <th>Hex</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="color in listOfColors.data" :key="color.id">
          <th>{{ color.name }}</th>
          <th>{{ color.hex }}</th>
          <th>
            <button class="button is-danger">
              <span class="icon">
                <font-awesome-icon icon="fa-solid fa-trash" />
              </span>
            </button>
          </th>
        </tr>
      </tbody>
    </table>
    <section v-else class="notification is-warning is-light">
      <h2 class="subtitle is-2">No Colors, yet.</h2>
      <p>No colors in the system, yet! Create a new one!</p>
    </section>
  </div>
</template>
