// frontend-vue-ts/src/components/ConfirmationModal.vue
<script setup lang="ts">
import Modal from "./Modal.vue";
import ModalStore from "../stores/ModalStore";

const emit = defineEmits(["confirm", "cancel"]);

const handleConfirm = () => emit("confirm");
const handleCancel = () => emit("cancel");
</script>

<template>
  <Modal :is-open="ModalStore.isConfirmationOpen" title="Are you sure?">
    <slot></slot>
    <template v-slot:buttons>
      <button class="button" @click="handleCancel">Cancel</button>
      <button class="button is-success" @click="handleConfirm">Confirm</button>
    </template>
  </Modal>
</template>

// frontend-react-ts/src/components/ConfirmationModal.tsx
import ModalContext from "../contexts/ModalContext";
import Modal from "./Modal";

interface ConfirmationModalProps {
  children: JSX.Element;
  onCancel: () => void;
  onConfirm: () => void;
}

const ConfirmationModal = (props: ConfirmationModalProps) => {
  return (
    <ModalContext.Consumer>
      {(context) => (
        <Modal
          isOpen={context.isConfirmationOpen}
          children={props.children}
          title="Are you sure?"
          actions={
            <>
              <button className="button" onClick={props.onCancel}>
                Cancel
              </button>
              <button className="button is-success" onClick={props.onConfirm}>
                Confirm
              </button>
            </>
          }
        ></Modal>
      )}
    </ModalContext.Consumer>
  );
};

export default ConfirmationModal;
