// frontend-vue-ts/src/components/CreationModal.vue
<script setup lang="ts">
interface CreationModalProps {
  title: string;
}

const props = defineProps<CreationModalProps>();

const emit = defineEmits(["save", "cancel", "close"]);

const onCloseClick = () => emit("close");
const onSaveClick = () => emit("save");
const onCancelClick = () => emit("cancel");
</script>

<template>
  <div class="modal">
    <div class="modal-background"></div>
    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title">{{ props.title }}</p>
        <button
          class="delete"
          aria-label="close"
          @click="onCloseClick"
        ></button>
      </header>
      <section class="modal-card-body">
        <slot></slot>
      </section>
      <footer class="modal-card-foot">
        <button class="button is-success" @click="onSaveClick">Save</button>
        <button class="button" @click="onCancelClick">Cancel</button>
      </footer>
    </div>
  </div>
</template>

// frontend-react-ts/src/components/CreationModal.tsx
interface CreationModalProps {
  title: string;
  className?: string;
  children: JSX.Element;
  isOpen: boolean;
  onCancel: () => void;
  onSave: () => void;
}

const CreationModal = (props: CreationModalProps) => {
  let className = "modal";
  if (props.isOpen) {
    className += " is-active";
  }
  return (
    <div className={className}>
      <div className="modal-background"></div>
      <div className="modal-card">
        <header className="modal-card-head">
          <p className="modal-card-title">{props.title}</p>
        </header>
        <section className="modal-card-body">{props.children}</section>
        <footer className="modal-card-foot">
          <button className="button is-success" onClick={props.onSave}>
            Save
          </button>
          <button className="button" onClick={props.onCancel}>
            Cancel
          </button>
        </footer>
      </div>
    </div>
  );
};

export default CreationModal;
