// frontend-react-ts/src/components/Modal.tsx
interface CreationModalProps {
  title: string;
  children: JSX.Element;
  actions: JSX.Element;
  isOpen: boolean;
}

const Modal = (props: CreationModalProps) => {
  let className = "modal";
  if (props.isOpen) {
    className += " is-active";
  }
  return (
    <div className={className}>
      <div className="modal-background"></div>
      <div className="modal-card">
        <header className="modal-card-head">
          <p className="modal-card-title">{props.title}</p>
        </header>
        <section className="modal-card-body">{props.children}</section>
        <footer className="modal-card-foot">{props.actions}</footer>
      </div>
    </div>
  );
};

export default Modal;

// frontend-vue-ts/src/components/Modal.vue
<script setup lang="ts">
import { computed } from "vue";

interface ModalProps {
  isOpen: boolean;
  title: string;
}

const props = defineProps<ModalProps>();

const modalClass = computed(() => {
  let className = "modal";
  if (props.isOpen) {
    className += " is-active";
  }
  return className;
});
</script>

<template>
  <div :class="modalClass">
    <div class="modal-background"></div>
    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title">{{ props.title }}</p>
      </header>
      <section class="modal-card-body">
        <slot></slot>
      </section>
      <footer class="modal-card-foot">
        <slot name="buttons"></slot>
      </footer>
    </div>
  </div>
</template>
